name: beauty_app_mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:

  country_flags: ^3.2.0
  cupertino_icons: ^1.0.8
  device_preview: ^1.2.0
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_multi_formatter: ^2.13.0
  flutter_native_splash: ^2.4.5
  flutter_rating: ^2.0.2
  flutter_riverpod: ^2.6.1
  flutter_rounded_date_picker: ^3.0.4
  flutter_staggered_grid_view: ^0.7.0
  fluttertoast: ^8.2.12
  gap: ^3.0.1
  geolocator: ^13.0.2
  icons_plus: ^5.0.0
  image_picker: ^1.1.2
  mobile_scanner: ^6.0.7
  permission_handler: ^11.4.0
  pinput: ^5.0.1
  readmore: ^3.0.0
  shared_preferences: ^2.5.2
  slide_countdown: ^2.0.2
  sliver_tools: ^0.2.12
  ultimate_flutter_icons: ^1.3.0

dev_dependencies:

  flutter_launcher_icons: "^0.14.3"
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logo.png"
  adaptive_icon_background: "#FFFFFF"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/logo/logo-splash.png
  color_dark: "#000000"

  android_12:
    color: "#FFFFFF"
    image: assets/logo/logo-splash.png
    color_dark: "#000000"

flutter:

  uses-material-design: true
  
  assets:
    - assets/images/
  
  fonts:
    - family: PoppinsExtraBold
      fonts:
        - asset: assets/fonts/Poppins-ExtraBold.ttf

    - family: PoppinsBold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf

    - family: PoppinsRegular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

    - family: PoppinsLight
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
