name: beauty_app_mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:

  country_flags: ^3.2.0
  cupertino_icons: ^1.0.8
  device_preview: ^1.2.0
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_multi_formatter: ^2.13.0
  flutter_riverpod: ^2.6.1
  flutter_rounded_date_picker: ^3.0.4
  fluttertoast: ^8.2.12
  gap: ^3.0.1
  geolocator: ^13.0.2
  icons_plus: ^5.0.0
  pinput: ^5.0.1
  shared_preferences: ^2.5.2
  slide_countdown: ^2.0.2

dev_dependencies:

  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  
  assets:
    - assets/
  
  fonts:
    - family: PoppinsExtraBold
      fonts:
        - asset: assets/fonts/Poppins-ExtraBold.ttf

    - family: PoppinsBold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf

    - family: PoppinsRegular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

    - family: PoppinsLight
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
