name: Flutter APK CI 

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Flutter APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          cache: true  

      - name: Build APK
        run: flutter build apk --split-per-abi --no-tree-shake-icons

      - name: Create release branch and upload APK
        run: |
          git config user.name "RKcod"
          git config user.email "ronaldobarthez.dev@gmail.com"
          git checkout --orphan apk-release
          git rm -rf .
          mkdir apk
          cp build/app/outputs/flutter-apk/app-arm64-v8a-release.apk apk/app-release.apk
          git add apk/app-release.apk
          git commit -m "Add APK"
          git push -f https://${{ secrets.FLUTTER_TOKEN }}@github.com/RKcod/Beauty_App_Mobile.git HEAD:apk-release