name: Flutter APK CI

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Flutter APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --split-per-abi

      - name: Create release branch and upload APK
        run: |
          git config user.name "RKcod"
          git config user.email "ronaldobarthez.dev@gmail.com"
          git checkout --orphan apk-release
          git rm -rf .
          mkdir apk
          cp build/app/outputs/flutter-apk/app-release.apk apk/
          git add apk/app-release.apk
          git commit -m "Add release APK"
          git push -f origin apk-release
