name: Flutter APK CI 

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Flutter APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          cache: true  

      - name: Build APK
        run: flutter build apk --split-per-abi --no-tree-shake-icons

      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
